apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datavolmodels
  namespace: kf1
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: nasavolmodels
