apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datavolrf
  namespace: kf1
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nasa-rf-test
