apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datavolxgb
  namespace: kf1
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nasa-xgb-test
