apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fraud-consumer-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: fraud-consumersc
