apiVersion: v1
kind: Service
metadata:
  name: spark-ui-service
  labels:
    app: spark-ui-service
spec:
  selector:
    component: spark-master
  type: NodePort
  ports:
    - nodePort: 31000
      port: 8080
      targetPort: 8080

