---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: spark-master
  labels:
    app: spark-master
spec:
  serviceName: spark-master-headless
  replicas: 1
  selector:
    matchLabels:
      component: spark-master
  template:
    metadata:
      labels:
        component: spark-master
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nodetype
                operator: In
                values:
                - wn01
      containers:
        - name: spark-master
          image: sachin944/spark:9.0
          securityContext:
            allowPrivilegeEscalation: false
            seLinuxOptions:
              level: "s0:c123,c456"
#            readOnlyRootFilesystem: true
          command: ["/spark-master"]
          ports:
            - containerPort: 7077
            - containerPort: 8080
            - containerPort: 4040
            - containerPort: 40694
          resources:
            requests:
              cpu: 2000m
              memory: 10Gi
          volumeMounts:
          - name: spark-master-mapr
            mountPath: /mnt
            readOnly: false
#      securityContext:
#        runAsUser: 1000
#        fsGroup: 1000
  volumeClaimTemplates:
  - metadata:
      name: spark-master-mapr
      namespace: default
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: sparksc
      resources:
        requests:
          storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: spark-master-headless
spec:
  clusterIP: None
  selector:
    component: spark-master

