apiVersion: v1
kind: Service
metadata:
  name: spark-driver
spec:
  clusterIP: None
  selector:
    component: spark-master
  ports:
    - protocol: TCP
      port: 40694
      targetPort: 40694
      name: spark-driver-port

