apiVersion: v1
kind: PersistentVolume
metadata:
  name: fraud-producervol
  labels:
    name: fraud-producervol
spec:
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: fraud-producersc
  capacity:
    storage: 5Gi
  csi:
    nodePublishSecretRef:
      name: "mapr-ticket-secret"
      namespace: "default"
    driver: com.mapr.csi-kdf
    volumeHandle: fraud-producervol
    volumeAttributes:
      volumePath: "/fraud_data"
      cluster: "datapipeline-ecp.cluster.com"
      cldbHosts: "172.30.203.1,172.30.203.2,172.30.203.3"
      securityType: "secure"
      platinum: "false"
      replication: "1"

