workerReplicas: 2
image: sachin944/spark:9.0
resources:
  cpu: 4000m
  memory: 25Gi
  storage: 10Gi
nodes:
- wn02
- wn03
secrets:
  maprUserSecret: "mapr-provisioner-secrets"
  maprClusterSecret: "mapr-ticket-secret"
restServers: "172.30.214.1:8443"
cldbHosts: "172.30.214.1:7222"
cluster: "hpe-epa-datapipeline.cluster.com"
replication: 1
