grafanaReplicas: 1
image: grafana/grafana:7.4.1
resources:
  storage: 10Gi
  memory: 10Gi
  cpu: 1000m
plugins: redis-datasource,https://github.com/HadesArchitect/GrafanaCassandraDatasource/releases/download/0.4.2/cassandra-datasource-0.4.2.zip;custom-plugin
unsigned: hadesarchitect-cassandra-datasource
nodes:
- wn01
secrets:
  maprUserSecret: "mapr-provisioner-secrets"
  maprClusterSecret: "mapr-ticket-secret"
restServers: "172.30.214.1:8443"
cldbHosts: "172.30.214.1:7222"
cluster: "hpe-epa-datapipeline.cluster.com"
replication: 1

